const JWT_SECRET = process.env.JWT_SECRET || 'lifebeforedeathstengthbeforeweaknessjourneybeforedestinationiwillprotectthosewhocannotprotectthemselvesiwillprotecteventhoseihatesolongasitisrightiacceptthattherewillbethosewhoicannotprotect'

module.exports = JWT_SECRET